### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by anishagrwl** [SAP/e-mobility-charging-stations-simulator#1035] opened 2024-04-28 05:35 UTC
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Component

Web UI

### Description

It doesn't show any charger template available in the UI while trying to add a new machine in the application. Not able to add any machine for simulation due to that. Please help.

### Version

1.3.2

### Node.js version

18.13.0

### System

NA

### Expected result

NA

**Comment by jerome-benoit** [comment] 2024-04-28 08:29
Not a bug report => closing.

**Closed by jerome-benoit** 2024-04-28 08:29 UTC
Labels: bug, triage
